## Load Libraries

In [124]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import sys
sys.path.append("../")
# import geopy
from geopy import distance
import math
import os

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

### Locations and Distances for government sensors

In [3]:
# location_df = pd.read_csv("/scratch/ab9738/pollution_img/govdata/locations.csv")

# location_df = location_df.drop(["source"], axis=1)

# columns = [loc for loc in location_df['id']]

# distance_df = pd.DataFrame(columns = [columns])

# for i, locx in enumerate(columns):
#     distance_df.loc[locx] = 0
#     for j,locy in enumerate(columns):
#         cord_x = (location_df.loc[i]['lat'], location_df.loc[i]['lon'])
#         cord_y = (location_df.loc[j]['lat'], location_df.loc[j]['lon'])
#         distance_df.loc[locx][locy] = distance.distance(cord_x, cord_y).kilometers

# distance_df.replace(0, np.nan, inplace=True)

### Locations and distances for combined government and kaiterra sensors

In [26]:
location_df = pd.read_excel("/scratch/ab9738/pollution_img/govdata/CombinedLocations.xlsx",engine='openpyxl')

In [29]:
location_df = location_df.drop(['Loc', 'Short Location', 'Address (as per lat-lon)'], axis=1)

In [152]:
# Adding UP Sensor Locations
location_df.loc[len(location_df)] = ['SanjayNagar_UPPCP', '28.685382,77.453839']
location_df.loc[len(location_df)] = ['Indirapuram_UPPCP', '28.646233,77.358075']
location_df.loc[len(location_df)] = ['Vasundhara_UPPCP', '28.6603346,77.3572563']
location_df.loc[len(location_df)] = ['Loni_UPPCP', '28.757294,77.278792']
location_df.loc[len(location_df)] = ['NoidaSector62_IMD', '28.6245479,77.3577104']
location_df.loc[len(location_df)] = ['NoidaSector116_UPPCP', '28.56912141,77.3939069']
location_df.loc[len(location_df)] = ['KnowledgeParkV_UPPCP', '28.55856132,77.45445483']
location_df.loc[len(location_df)] = ['KnowledgeParkIII_UPPCP', '28.47250249,77.48179193']
location_df.loc[len(location_df)] = ['NoidaSector1_UPPCP', '28.58966084,77.30998866']
location_df.loc[len(location_df)] = ['NoidaSector125_UPPCP', '28.54492244,77.32281108']

In [153]:
location_df

                Monitor ID                  Lat-Lon
0                     1FD7        28.56502,77.19097
1                     2E9C      28.523288,77.193379
2                     3ACF      28.536967,77.203255
3                     4BE7    28.5328704,77.2171122
4                     5D7A      28.482569,77.100401
..                     ...                      ...
66    NoidaSector116_UPPCP   28.56912141,77.3939069
67    KnowledgeParkV_UPPCP  28.55856132,77.45445483
68  KnowledgeParkIII_UPPCP  28.47250249,77.48179193
69      NoidaSector1_UPPCP  28.58966084,77.30998866
70    NoidaSector125_UPPCP  28.54492244,77.32281108

[71 rows x 2 columns]

In [154]:
columns = [loc for loc in location_df['Monitor ID']]

In [155]:
distance_df = pd.DataFrame(columns = [columns])

In [156]:
for i, locx in enumerate(columns):
    distance_df.loc[locx] = 0
    for j,locy in enumerate(columns):
        cord_x = (float(location_df.loc[i]['Lat-Lon'].split(',')[0]),\
                  float(location_df.loc[i]['Lat-Lon'].split(',')[1]))
        cord_y = (float(location_df.loc[j]['Lat-Lon'].split(',')[0]),\
                  float(location_df.loc[j]['Lat-Lon'].split(',')[1]))
        distance_df.loc[locx][locy] = distance.distance(cord_x, cord_y).kilometers

In [157]:
distance_df.replace(0, np.nan, inplace=True)

In [158]:
distance_df

,1FD7,2E9C,3ACF,4BE7,5D7A,8E2A,20CA,56C3,72CA,91B8,...,SanjayNagar_UPPCP,Indirapuram_UPPCP,Vasundhara_UPPCP,Loni_UPPCP,NoidaSector62_IMD,NoidaSector116_UPPCP,KnowledgeParkV_UPPCP,KnowledgeParkIII_UPPCP,NoidaSector1_UPPCP,NoidaSector125_UPPCP
1FD7,NaN,4.631090,3.333396,4.386367,12.731477,12.117227,3.111082,3.257005,17.198875,6.887653,...,28.960660,18.658471,19.392499,22.974090,17.593771,19.860981,25.791137,30.257885,11.959871,13.091956
2E9C,4.631090,NaN,1.797964,2.554211,10.159921,8.846528,6.504179,2.980613,14.132738,2.366795,...,31.172202,21.100826,22.083251,27.246263,19.606897,20.270717,25.847858,28.792846,13.576075,12.892771
3ACF,3.333396,1.797964,NaN,1.430207,11.735812,10.558792,5.866121,1.236795,14.225369,4.134732,...,29.515676,19.390753,20.343225,25.511155,17.959310,18.993564,24.698635,28.189082,11.965385,11.733683
4BE7,4.386367,2.554211,1.430207,NaN,12.713154,11.346276,7.171915,1.221304,12.896397,4.516796,...,28.666137,18.654539,19.684479,25.593451,17.100690,17.760972,23.400661,26.762346,11.054470,10.430436
5D7A,12.731477,10.159921,11.735812,12.713154,NaN,2.332924,11.799929,12.969119,21.315502,8.650870,...,41.239657,31.058900,31.932395,35.091318,29.691358,30.287567,35.665252,37.364289,23.698748,22.842425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NoidaSector116_UPPCP,19.860981,20.270717,18.993564,17.760972,30.287567,28.603589,22.788148,17.875984,14.679509,21.656795,...,14.155291,9.236863,10.725746,23.697382,7.090157,NaN,6.038817,13.735640,8.519529,7.455886
KnowledgeParkV_UPPCP,25.791137,25.847858,24.698635,23.400661,35.665252,33.843033,28.760244,23.633281,17.694699,27.018236,...,14.055608,13.538007,14.751137,27.928802,11.959974,6.038817,NaN,9.906011,14.548130,12.970552
KnowledgeParkIII_UPPCP,30.257885,28.792846,28.189082,26.762346,37.364289,35.213556,33.368956,27.410921,16.343784,29.192840,...,23.751149,22.743649,24.121083,37.287790,20.770054,13.735640,9.906011,NaN,21.245002,17.511266
NoidaSector1_UPPCP,11.959871,13.576075,11.965385,11.054470,23.698748,22.400679,14.663976,10.736583,14.828662,15.497563,...,17.617509,7.837454,9.094884,18.827419,6.060923,8.519529,14.548130,21.245002,NaN,5.114553
NoidaSector125_UPPCP,13.091956,12.892771,11.733683,10.430436,22.842425,21.148046,16.163700,10.693435,9.881590,14.204078,...,20.162769,11.746051,13.227294,23.927334,9.462186,7.455886,12.970552,17.511266,5.114553,NaN

### Finding close-by sensors

In [159]:
def find_closeby(dist_df, radius):
    location_list = list(dist_df.index)
    num_locs = len(location_list)
    loc_pairs = []
    for i, locx in enumerate(location_list):
        for j in range(i+1, num_locs):
            if(dist_df.loc[locx][location_list[j]][0]<radius):
                loc_pairs.append((locx,location_list[j]))
    return loc_pairs

In [160]:
find_closeby(distance_df, 1.0)

[('1FD7', '97D7'),
 ('1FD7', 'E8E4'),
 ('1FD7', 'RKPuram_DPCC'),
 ('2E9C', 'SriAurobindoMarg_DPCC'),
 ('3ACF', 'E47A'),
 ('56C3', 'E47A'),
 ('56C3', 'Sirifort_CPCB'),
 ('97D7', 'E8E4'),
 ('498F', 'DF07'),
 ('603A', 'CBC7'),
 ('A9BE', 'Sirifort_CPCB'),
 ('E1F8', 'JNS_DPCC'),
 ('EAC8', 'SriAurobindoMarg_DPCC'),
 ('Pusa_DPCC', 'Pusa_IMD')]

### Load the government and kaiterra data

In [74]:
govdata = pd.read_csv('/scratch/ab9738/pollution_img/govdata/govdata_1H_20180501_20201101.csv',\
                      index_col='monitor_id', usecols=['monitor_id','timestamp_round','pm10'])

In [85]:
govdata

                           timestamp_round   pm10
monitor_id
AnandVihar_DPCC  2018-05-01 00:00:00+05:30  295.0
AnandVihar_DPCC  2018-05-01 01:00:00+05:30  202.0
AnandVihar_DPCC  2018-05-01 02:00:00+05:30  163.0
AnandVihar_DPCC  2018-05-01 03:00:00+05:30  140.0
AnandVihar_DPCC  2018-05-01 04:00:00+05:30  151.0
...                                    ...    ...
Wazirpur_DPCC    2020-10-31 19:00:00+05:30  377.0
Wazirpur_DPCC    2020-10-31 20:00:00+05:30  430.5
Wazirpur_DPCC    2020-10-31 21:00:00+05:30  468.5
Wazirpur_DPCC    2020-10-31 22:00:00+05:30  509.0
Wazirpur_DPCC    2020-10-31 23:00:00+05:30  580.5

[702720 rows x 2 columns]

In [80]:
kaidata = pd.read_csv('/scratch/ab9738/pollution_img/govdata/kaiterra_fieldeggid_1H_20180501_20201101.csv',\
                      index_col='field_egg_id', usecols=['field_egg_id','timestamp_round','pm10'])

In [82]:
kaidata = kaidata.dropna()

In [86]:
kaidata

                        timestamp_round       pm10
field_egg_id
113E          2018-06-21 16:00:00+05:30  47.857143
113E          2018-06-21 17:00:00+05:30  40.250000
113E          2018-06-21 18:00:00+05:30  42.272727
113E          2018-06-21 19:00:00+05:30  37.833333
113E          2018-06-21 20:00:00+05:30  35.833333
...                                 ...        ...
EAC8          2020-07-11 02:00:00+05:30   7.714286
EAC8          2020-07-11 03:00:00+05:30   9.166667
EAC8          2020-07-11 04:00:00+05:30   7.800000
EAC8          2020-07-11 05:00:00+05:30   7.666667
EAC8          2020-07-11 06:00:00+05:30  10.000000

[202110 rows x 2 columns]

In [108]:
fulldata = pd.concat([govdata, kaidata])

In [109]:
fulldata = fulldata.loc[~(fulldata==0).all(axis=1)]
fulldata

                           timestamp_round        pm10
AnandVihar_DPCC  2018-05-01 00:00:00+05:30  295.000000
AnandVihar_DPCC  2018-05-01 01:00:00+05:30  202.000000
AnandVihar_DPCC  2018-05-01 02:00:00+05:30  163.000000
AnandVihar_DPCC  2018-05-01 03:00:00+05:30  140.000000
AnandVihar_DPCC  2018-05-01 04:00:00+05:30  151.000000
...                                    ...         ...
EAC8             2020-07-11 02:00:00+05:30    7.714286
EAC8             2020-07-11 03:00:00+05:30    9.166667
EAC8             2020-07-11 04:00:00+05:30    7.800000
EAC8             2020-07-11 05:00:00+05:30    7.666667
EAC8             2020-07-11 06:00:00+05:30   10.000000

[904830 rows x 2 columns]

### Estimate the sensor substitution error

In [161]:
pairs = find_closeby(distance_df, 0.5)

In [162]:
pairs

[('1FD7', 'RKPuram_DPCC'),
 ('97D7', 'E8E4'),
 ('603A', 'CBC7'),
 ('Pusa_DPCC', 'Pusa_IMD')]

In [163]:
def mean_rel_abs_error(df1, df2):
    assert(df1.index == df2.index).all()
    if(len(list(df1.index))):
        total_rel_err = 0
        total_valid_len = 0
        for ind in list(df1.index):
            rel_err = abs(df2.loc[ind][0]-df1.loc[ind][0])/df1.loc[ind][0]
            if(not math.isnan(rel_err)):
                total_rel_err += rel_err
                total_valid_len += 1
        mean_err = total_rel_err/total_valid_len
        return mean_err

In [164]:
mean_sensor_subserrors = []

In [165]:
for indv_pair in pairs:
    df1 = fulldata.loc[indv_pair[0]].set_index('timestamp_round')
    df2 = fulldata.loc[indv_pair[1]].set_index('timestamp_round')
    common_timestamps = list(set(list(df1.index)).intersection(list(df2.index)))
    mean_sensor_subserrors.append(mean_rel_abs_error(df1.loc[common_timestamps], df2.loc[common_timestamps]))
    mean_sensor_subserrors.append(mean_rel_abs_error(df2.loc[common_timestamps], df1.loc[common_timestamps]))

<ipython-input-163-34649d0da35e>:7: RuntimeWarning: divide by zero encountered in double_scalars
  rel_err = abs(df2.loc[ind][0]-df1.loc[ind][0])/df1.loc[ind][0]

In [166]:
mean_sensor_subserrors

[1.9719378323893502,
 inf,
 0.5070585084414171,
 0.30752974386862003,
 0.17660986294654354,
 0.1697659301670889,
 0.3086718390482951,
 0.5454097786258302]

### Calculate Image Distances

In [134]:
image_list = os.listdir('/scratch/ab9738/pollution_img/new_images/')

In [135]:
img_latlong_list = []

In [136]:
for image in image_list:
    latlong_str = image.split('___')[1]
    latlong_tuple = tuple(latlong_str.split('_'))
    img_latlong_list.append(latlong_tuple)

In [138]:
img_latlong_list = [(float(lat), float(long)) for lat, long in img_latlong_list]

In [139]:
img_latlong_list

[(28.661858, 77.314443),
 (28.664578, 77.393921),
 (28.475996, 77.483764),
 (28.630176, 77.326735),
 (28.635686, 77.393773),
 (28.540366, 77.33232),
 (28.631465, 77.364205),
 (28.649286, 77.379147),
 (28.660801, 77.377701),
 (28.688277, 77.451112),
 (28.585753, 77.310184),
 (28.628635, 77.364955),
 (28.552655, 77.105907),
 (28.63739, 77.314455),
 (28.569345, 77.216624),
 (28.695991, 77.441333),
 (28.644784, 77.313864),
 (28.648623, 77.304227),
 (28.648374, 77.303762),
 (28.58925, 77.154483),
 (28.474239, 77.485458),
 (28.661537, 77.464322),
 (28.644775, 77.314376),
 (28.633781, 77.282711),
 (28.667866, 77.314722),
 (28.64911, 77.318156),
 (28.584914, 77.230163),
 (28.647227, 77.379171),
 (28.605417, 77.226652),
 (28.531033, 77.362267),
 (28.636282, 77.443121),
 (28.662044, 77.314296),
 (28.635229, 77.45851),
 (28.629601, 77.27662),
 (28.627126, 77.317232),
 (28.688788, 77.45196),
 (28.691533, 77.438049),
 (28.605513, 77.289196),
 (28.631952, 77.370305),
 (28.596983, 77.292413),
 (28.629866, 77.312303),
 (28.635858, 77.36872),
 (28.648815, 77.318503),
 (28.520557, 77.375688),
 (28.560304, 77.26133),
 (28.628434, 77.320904),
 (28.632295, 77.347338),
 (28.6353, 77.368761),
 (28.639326, 77.370339),
 (28.658448, 77.466949),
 (28.636529, 77.440383),
 (28.593439, 77.16431),
 (28.640848, 77.29518),
 (28.586256, 77.310865),
 (28.652166, 77.307214),
 (28.65329, 77.308303),
 (28.632879, 77.305535),
 (28.640517, 77.462835),
 (28.513139, 77.469933),
 (28.647714, 77.371573),
 (28.469869, 77.452254),
 (28.689384, 77.452506),
 (28.63358, 77.387399),
 (28.659664, 77.315699),
 (28.638392, 77.430554),
 (28.654088, 77.37699),
 (28.662948, 77.314671),
 (28.589858, 77.219124),
 (28.658526, 77.310567),
 (28.630825, 77.366612),
 (28.574809, 77.142414),
 (28.526838, 77.472558),
 (28.627761, 77.242745),
 (28.634425, 77.304852),
 (28.633694, 77.443769),
 (28.629418, 77.306854),
 (28.656883, 77.31044),
 (28.646038, 77.369576),
 (28.644754, 77.316384),
 (28.644585, 77.316757),
 (28.517161, 77.470356),
 (28.621001, 77.299953),
 (28.559959, 77.26179),
 (28.609228, 77.22877),
 (28.664979, 77.456227),
 (28.629853, 77.312269),
 (28.653136, 77.47164),
 (28.589783, 77.218424),
 (28.61489, 77.234102),
 (28.551897, 77.329415),
 (28.629552, 77.30684),
 (28.629879, 77.312289),
 (28.566263, 77.252921),
 (28.468129, 77.490014),
 (28.693928, 77.455003),
 (28.66066, 77.377206),
 (28.6292, 77.36497),
 (28.593151, 77.234143),
 (28.645953, 77.370585),
 (28.555626, 77.265396),
 (28.648928, 77.317168),
 (28.673794, 77.455285),
 (28.586185, 77.311186),
 (28.673644, 77.455273),
 (28.543966, 77.32795),
 (28.588653, 77.233805),
 (28.586073, 77.212744),
 (28.629866, 77.312303),
 (28.666481, 77.315335),
 (28.591952, 77.235666),
 (28.57651, 77.210986),
 (28.687307, 77.450782),
 (28.68839, 77.451291),
 (28.659796, 77.310875),
 (28.687681, 77.450516),
 (28.556887, 77.327238),
 (28.646525, 77.313775),
 (28.60649, 77.22675),
 (28.629943, 77.311941),
 (28.651697, 77.306612),
 (28.574009, 77.215078),
 (28.631106, 77.361334),
 (28.585078, 77.311949),
 (28.673617, 77.415522),
 (28.687843, 77.450551),
 (28.673061, 77.455542),
 (28.630763, 77.311556),
 (28.655187, 77.376898),
 (28.553902, 77.123568),
 (28.673095, 77.415145),
 (28.630805, 77.31503),
 (28.58456, 77.229727),
 (28.628106, 77.266335),
 (28.6283, 77.313009),
 (28.566461, 77.253072),
 (28.651876, 77.319508),
 (28.640972, 77.301731),
 (28.630685, 77.311382),
 (28.629879, 77.312289),
 (28.538931, 77.33547),
 (28.632224, 77.442823),
 (28.690338, 77.436391),
 (28.632938, 77.315547),
 (28.68789, 77.450336),
 (28.541204, 77.330962),
 (28.559536, 77.262061),
 (28.586256, 77.310865),
 (28.666043, 77.315389),
 (28.66543, 77.315212),
 (28.569295, 77.211107),
 (28.690455, 77.453634),
 (28.658751, 77.375745),
 (28.628075, 77.315811),
 (28.635244, 77.305182),
 (28.617153, 77.28827),
 (28.665051, 77.314673),
 (28.617455, 77.289189),
 (28.630658, 77.311242),
 (28.650288, 77.378712),
 (28.68349, 77.453589),
 (28.631498, 77.369746),
 (28.643081, 77.316336),
 (28.64819, 77.318162),
 (28.516838, 77.380876),
 (28.631146, 77.306302),
 (28.565631, 77.248562),
 (28.562157, 77.252258),
 (28.668447, 77.399697),
 (28.628146, 77.248471),
 (28.456691, 77.499804),
 (28.657815, 77.376015),
 (28.602359, 77.231628),
 (28.56573, 77.333385),
 (28.631957, 77.358967),
 (28.641457, 77.374256),
 (28.575947, 77.143855),
 (28.643855, 77.46511),
 (28.609396, 77.191246),
 (28.628467, 77.312745),
 (28.584698, 77.229692),
 (28.57506, 77.216114),
 (28.615016, 77.23396),
 (28.602459, 77.231698),
 (28.590508, 77.23351),
 (28.693192, 77.445938),
 (28.454527, 77.497691),
 (28.635845, 77.285284),
 (28.584855, 77.227551),
 (28.644787, 77.315188),
 (28.682, 77.426624),
 (28.632722, 77.442254),
 (28.477578, 77.482202),
 (28.660216, 77.465921),
 (28.645898, 77.372903),
 (28.629899, 77.436394),
 (28.655545, 77.319781),
 (28.605034, 77.186616),
 (28.667685, 77.314507),
 (28.500052, 77.484509),
 (28.634871, 77.28421),
 (28.692686, 77.445712),
 (28.631513, 77.367531),
 (28.620924, 77.237631),
 (28.534517, 77.353514),
 (28.629879, 77.312289),
 (28.62758, 77.242526),
 (28.565262, 77.242233),
 (28.66817, 77.314503),
 (28.644124, 77.316652),
 (28.551897, 77.329415),
 (28.66063, 77.377365),
 (28.635331, 77.45209),
 (28.632168, 77.337596),
 (28.673181, 77.415627),
 (28.592869, 77.163121),
 (28.653782, 77.309092),
 (28.689384, 77.452506),
 (28.688076, 77.451064),
 (28.607535, 77.227378),
 (28.667685, 77.314507),
 (28.632168, 77.33547),
 (28.633933, 77.388772),
 (28.64001, 77.40836),
 (28.635774, 77.444579),
 (28.647647, 77.369527),
 (28.645836, 77.37199),
 (28.572522, 77.211804),
 (28.630305, 77.27738),
 (28.657976, 77.320062),
 (28.576343, 77.21096),
 (28.644216, 77.299148),
 (28.671335, 77.412624),
 (28.530274, 77.364564),
 (28.603315, 77.227148),
 (28.564872, 77.240077),
 (28.471369, 77.488126),
 (28.661858, 77.314443),
 (28.679488, 77.423914),
 (28.580738, 77.315232),
 (28.632443, 77.350381),
 (28.667114, 77.315098),
 (28.630327, 77.306664),
 (28.688822, 77.451802),
 (28.56632, 77.252954),
 (28.635733, 77.314658),
 (28.640177, 77.36905),
 (28.6238, 77.308013),
 (28.55705, 77.132781),
 (28.659549, 77.312785),
 (28.688991, 77.449516),
 (28.635203, 77.448388),
 (28.636658, 77.439067),
 (28.507446, 77.389299),
 (28.58775, 77.310007),
 (28.633938, 77.31528),
 (28.573109, 77.213182),
 (28.534394, 77.354487),
 (28.645056, 77.312288),
 (28.563273, 77.250395),
 (28.630825, 77.311407),
 (28.6329, 77.443162),
 (28.648781, 77.317658),
 (28.645056, 77.312288),
 (28.569063, 77.328703),
 (28.605417, 77.226652),
 (28.627783, 77.24257),
 (28.637357, 77.460731),
 (28.561069, 77.133684),
 (28.469431, 77.489894),
 (28.546299, 77.329024),
 (28.596983, 77.292413),
 (28.662044, 77.314296),
 (28.629787, 77.312323),
 (28.657723, 77.319778),
 (28.628467, 77.312745),
 (28.586905, 77.310547),
 (28.569853, 77.332646),
 (28.668189, 77.314546),
 (28.689766, 77.453192),
 (28.671513, 77.411541),
 (28.632239, 77.305759),
 (28.556778, 77.263898),
 (28.568172, 77.25395),
 (28.546833, 77.329564),
 (28.657315, 77.319855),
 (28.644828, 77.314759),
 (28.621091, 77.237763),
 (28.65862, 77.379271),
 (28.585168, 77.234071),
 (28.636132, 77.286433),
 (28.629787, 77.312323),
 (28.635774, 77.444579),
 (28.62926, 77.316741),
 (28.631868, 77.375178),
 (28.630534, 77.435857),
 (28.631952, 77.370305),
 (28.675076, 77.417413),
 (28.572836, 77.209712),
 (28.6238, 77.308013),
 (28.639739, 77.292936),
 (28.61001, 77.232509),
 (28.657375, 77.31059),
 (28.576826, 77.319188),
 (28.59238, 77.234598),
 (28.470627, 77.488803),
 (28.592353, 77.234541),
 (28.659857, 77.376463),
 (28.63081, 77.311595),
 (28.672702, 77.401104),
 (28.647228, 77.302409),
 (28.672113, 77.409142),
 (28.645549, 77.374325),
 (28.67306, 77.405685),
 (28.64391, 77.299134),
 (28.562903, 77.250618),
 (28.563708, 77.133846),
 (28.68279, 77.427565),
 (28.63667, 77.397484),
 (28.556887, 77.327238),
 (28.629908, 77.277072),
 (28.670896, 77.413441),
 (28.611908, 77.284695),
 (28.63081, 77.311595),
 (28.647158, 77.317768),
 (28.514415, 77.471093),
 (28.692491, 77.439146),
 (28.570324, 77.254571),
 (28.580896, 77.212159),
 (28.585753, 77.310184),
 (28.584774, 77.226988),
 (28.680201, 77.424891),
 (28.647696, 77.37124),
 (28.577876, 77.318616),
 (28.569674, 77.210449),
 (28.629866, 77.312303),
 (28.636631, 77.439224),
 (28.633953, 77.454915),
 (28.631498, 77.369746),
 (28.569327, 77.328293),
 (28.631952, 77.370305),
 (28.585824, 77.234236),
 (28.644488, 77.31667),
 (28.631509, 77.367941),
 (28.66029, 77.313596),
 (28.56542, 77.246164),
 (28.530274, 77.364564),
 (28.570897, 77.209684),
 (28.629858, 77.325522),
 (28.627761, 77.242493),
 (28.693492, 77.439995),
 (28.630342, 77.435467),
 (28.6288, 77.323217),
 (28.458657, 77.499664),
 (28.656276, 77.376637),
 (28.552728, 77.328239),
 (28.575791, 77.218465),
 (28.653994, 77.471397),
 (28.628236, 77.271899),
 (28.65811, 77.376076),
 (28.629853, 77.312269),
 (28.690259, 77.453488),
 (28.634425, 77.304852),
 (28.621043, 77.237691),
 (28.628013, 77.247599),
 (28.589909, 77.220517),
 (28.665421, 77.315137),
 (28.644709, 77.299338),
 (28.672298, 77.415058),
 (28.640546, 77.420025),
 (28.667636, 77.314947),
 (28.474239, 77.485458),
 (28.631925, 77.373854),
 (28.647287, 77.378974),
 (28.670381, 77.456135),
 (28.666362, 77.398856),
 (28.568534, 77.253522),
 (28.695991, 77.441333),
 (28.632619, 77.280522),
 (28.592227, 77.234635),
 (28.649164, 77.304448),
 (28.653339, 77.377078),
 (28.689098, 77.452181),
 (28.690097, 77.453242),
 (28.641439, 77.31584),
 (28.657211, 77.376763),
 (28.632127, 77.367279),
 (28.631417, 77.368168),
 (28.663424, 77.460434),
 (28.565575, 77.245297),
 (28.630585, 77.311037),
 (28.565348, 77.243268),
 (28.614111, 77.234814),
 (28.587667, 77.233977),
 (28.584724, 77.212641),
 (28.677897, 77.421948),
 (28.64151, 77.374468),
 (28.550738, 77.120168),
 (28.636138, 77.314466),
 (28.566905, 77.133509),
 (28.584914, 77.230163),
 (28.562846, 77.250583),
 (28.636639, 77.286733),
 (28.665304, 77.455956),
 (28.632295, 77.347338),
 (28.660861, 77.377743),
 (28.64752, 77.302784),
 (28.633316, 77.365818),
 (28.574142, 77.322935),
 (28.673695, 77.4025),
 (28.648759, 77.316802),
 (28.569148, 77.253643),
 (28.67273, 77.407208),
 (28.671193, 77.413617),
 (28.627747, 77.242526),
 (28.576826, 77.319188),
 (28.665103, 77.45608),
 (28.687913, 77.450609),
 (28.631901, 77.34521),
 (28.646447, 77.301738),
 (28.631314, 77.316076),
 (28.659306, 77.310659),
 (28.62097, 77.237645),
 (28.671563, 77.415227),
 (28.638502, 77.314679),
 (28.68502, 77.429648),
 (28.652392, 77.307639),
 (28.641055, 77.29471),
 (28.676397, 77.419148),
 (28.63011, 77.437243),
 (28.65297, 77.308168),
 (28.627761, 77.242745),
 (28.654191, 77.31972),
 (28.590318, 77.223542),
 (28.660252, 77.376252),
 (28.635746, 77.369029),
 (28.630198, 77.32709),
 (28.645883, 77.372503),
 (28.585753, 77.310184),
 (28.66542, 77.315075),
 (28.649117, 77.304613),
 (28.617455, 77.289189),
 (28.661428, 77.386421),
 (28.553466, 77.327022),
 (28.54459, 77.327152),
 (28.629898, 77.312332),
 (28.662948, 77.314671),
 (28.565411, 77.250787),
 (28.562774, 77.250668),
 (28.635948, 77.28547),
 (28.505805, 77.393393),
 (28.632077, 77.340302),
 (28.581544, 77.303543),
 (28.547133, 77.329797),
 (28.644079, 77.316672),
 (28.642491, 77.31634),
 (28.573327, 77.138869),
 (28.69094, 77.454142),
 (28.63082, 77.311557),
 (28.634873, 77.304685),
 (28.673181, 77.415627),
 (28.629853, 77.312269),
 (28.603111, 77.227225),
 (28.570997, 77.326153),
 (28.639837, 77.293828),
 (28.660911, 77.377783),
 (28.633268, 77.30537),
 (28.630324, 77.441666),
 (28.575748, 77.218529),
 (28.547437, 77.329289),
 (28.609304, 77.19098),
 (28.658604, 77.375759),
 (28.603646, 77.289065),
 (28.520323, 77.467422),
 (28.47207, 77.487583),
 (28.630198, 77.32709),
 (28.555445, 77.095165),
 (28.551215, 77.330123),
 (28.573786, 77.323359),
 (28.557814, 77.263375),
 (28.631939, 77.305859),
 (28.589722, 77.218086),
 (28.656708, 77.376348),
 (28.639033, 77.314877),
 (28.61548, 77.233657),
 (28.535063, 77.345354),
 (28.629879, 77.312289),
 (28.568161, 77.224789),
 (28.593439, 77.16431),
 (28.631746, 77.44261),
 (28.531033, 77.362267),
 (28.628635, 77.364955),
 (28.646094, 77.313237),
 (28.657815, 77.376015),
 (28.574091, 77.322969),
 (28.611058, 77.285139),
 (28.59018, 77.296153),
 (28.631513, 77.367531),
 (28.627742, 77.243155),
 (28.628281, 77.364846),
 (28.636282, 77.443121),
 (28.66063, 77.377365),
 (28.575967, 77.218523),
 (28.559902, 77.26175),
 (28.66817, 77.314503),
 (28.61436, 77.284087),
 (28.575748, 77.218529),
 (28.682996, 77.427536),
 (28.629589, 77.441248),
 (28.640177, 77.36905),
 (28.64777, 77.370468),
 (28.636439, 77.441936)]

In [167]:
columns = [loc for loc in location_df['Monitor ID']]
imgdist_df = pd.DataFrame(columns = [columns])

In [168]:
for i, cord_x in enumerate(img_latlong_list):
    imgdist_df.loc[i] = 0
    for j,locy in enumerate(columns):
        cord_y = (float(location_df.loc[j]['Lat-Lon'].split(',')[0]),\
                  float(location_df.loc[j]['Lat-Lon'].split(',')[1]))
        imgdist_df.loc[i][locy] = distance.distance(cord_x, cord_y).kilometers

In [169]:
img_min_dist = imgdist_df.min(axis=1)

In [178]:
img_min_dist[img_min_dist<1]

2      0.432667
6      0.995506
9      0.417105
10     0.433523
11     0.840865
         ...
490    0.840865
491    0.285337
497    0.754610
498    0.811211
503    0.468267
Length: 167, dtype: float64